server:
  port: 8083
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456a?
  redis:
    host: 127.0.0.1
mybatis-plus:
  config-location: classpath:mapper/pms/*.xml
  global-config:
    db-config:
      id-type: auto
