server:
  port: 8086
spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    name: root
    password: 123456a?
  redis:
    host: 127.0.0.1
mybatis-plus:
  config-location: classpath:mapper/wms/*.xml
  global-config:
    db-config:
      id-type: auto